#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateSDMXConsole
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SDMX_DB")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertGeoArea(GeoArea instance);
    partial void UpdateGeoArea(GeoArea instance);
    partial void DeleteGeoArea(GeoArea instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::UpdateSDMXConsole.Properties.Settings.Default.SDMX_DBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<GeoArea> GeoAreas
		{
			get
			{
				return this.GetTable<GeoArea>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GeoAreas")]
	public partial class GeoArea : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _GeoCodeID;
		
		private System.Nullable<int> _GeoAreaCode;
		
		private string _GeoAreaName;
		
		private System.Nullable<double> _Longitude;
		
		private System.Nullable<double> _Latitude;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGeoCodeIDChanging(long value);
    partial void OnGeoCodeIDChanged();
    partial void OnGeoAreaCodeChanging(System.Nullable<int> value);
    partial void OnGeoAreaCodeChanged();
    partial void OnGeoAreaNameChanging(string value);
    partial void OnGeoAreaNameChanged();
    partial void OnLongitudeChanging(System.Nullable<double> value);
    partial void OnLongitudeChanged();
    partial void OnLatitudeChanging(System.Nullable<double> value);
    partial void OnLatitudeChanged();
    #endregion
		
		public GeoArea()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GeoCodeID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long GeoCodeID
		{
			get
			{
				return this._GeoCodeID;
			}
			set
			{
				if ((this._GeoCodeID != value))
				{
					this.OnGeoCodeIDChanging(value);
					this.SendPropertyChanging();
					this._GeoCodeID = value;
					this.SendPropertyChanged("GeoCodeID");
					this.OnGeoCodeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GeoAreaCode", DbType="Int")]
		public System.Nullable<int> GeoAreaCode
		{
			get
			{
				return this._GeoAreaCode;
			}
			set
			{
				if ((this._GeoAreaCode != value))
				{
					this.OnGeoAreaCodeChanging(value);
					this.SendPropertyChanging();
					this._GeoAreaCode = value;
					this.SendPropertyChanged("GeoAreaCode");
					this.OnGeoAreaCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GeoAreaName", DbType="VarChar(150)")]
		public string GeoAreaName
		{
			get
			{
				return this._GeoAreaName;
			}
			set
			{
				if ((this._GeoAreaName != value))
				{
					this.OnGeoAreaNameChanging(value);
					this.SendPropertyChanging();
					this._GeoAreaName = value;
					this.SendPropertyChanged("GeoAreaName");
					this.OnGeoAreaNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitude", DbType="Float")]
		public System.Nullable<double> Longitude
		{
			get
			{
				return this._Longitude;
			}
			set
			{
				if ((this._Longitude != value))
				{
					this.OnLongitudeChanging(value);
					this.SendPropertyChanging();
					this._Longitude = value;
					this.SendPropertyChanged("Longitude");
					this.OnLongitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitude", DbType="Float")]
		public System.Nullable<double> Latitude
		{
			get
			{
				return this._Latitude;
			}
			set
			{
				if ((this._Latitude != value))
				{
					this.OnLatitudeChanging(value);
					this.SendPropertyChanging();
					this._Latitude = value;
					this.SendPropertyChanged("Latitude");
					this.OnLatitudeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
